POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Wayne Dev",
  "dateOfBirth": "2001-07-14",
  "ssn": "123456-789X",
  "gender": "other",
  "occupation": "Software Engineer"
}

###
GET  http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667
Content-Type: application/json

